# Dockerfile containing software for Control C++ quizzes
FROM ubuntu:xenial

WORKDIR /quizzes

RUN apt-get update && apt-get install -y \
    build-essential \
    gcc \
    g++ \
    gfortran \
    cmake \
    pkg-config \
    unzip \
    git \
    wget \
    python-dev
#    cppad \
#    libblas-dev \
#    liblapack-dev

#RUN apt-get install -y coinor-libipopt-dev
#RUN wget https://www.coin-or.org/download/source/Ipopt/Ipopt-3.12.1.zip && unzip Ipopt-3.12.1 && rm Ipopt-3.12.1.zip


#COPY ./install_ipopt.sh .

#RUN bash install_ipopt.sh Ipopt-3.12.1
#RUN bash install_ipopt.sh Ipopt


RUN rm -rf /var/lib/apt/lists/*

RUN git clone https://github.com/coin-or/Ipopt.git

WORKDIR Ipopt

RUN git clone https://github.com/coin-or-tools/BuildTools 

RUN ./BuildTools/get.dependencies.sh fetch --git 
RUN ./BuildTools/get.dependencies.sh build --quiet --test
RUN ./BuildTools/get.dependencies.sh install --prefix=/usr/local

#RUN ./configure --prefix=/usr/local && make && make install

RUN ldconfig -v

WORKDIR ..

RUN git clone https://github.com/CSCsw/CppAD.git
WORKDIR CppAD
RUN cmake . && make install

RUN ldconfig -v

ADD . /quizzes

WORKDIR ../mpc_to_line

RUN mkdir build && cd build && cmake .. && make
